[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers --html=reports/report.html --self-contained-html --log-cli-level=INFO
log_cli = true
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S
markers =
    smoke: Smoke tests
    regression: Regression tests
    mobile: Mobile emulation tests
